name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: riscv-builders

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -march="rv64gvzve64x" ghostwrite.c -o ghostwrite
    - name: ghostwrite
      run: ./ghostwrite
